### ISSUE TITLE
MethodDecorator attribute on method in interface should be cascaded to implementation.

### ISSUE THREAD

**Issue by a11smiles** [Fody/MethodDecorator#118]
Consider the following:

```csharp
public interface ITestMe
{
   [NotNull]
   Task DoSomething();
}

public class TestMe : ITestMe
{
   public async Task DoSomething() 
   {
      // do something
   }
}
```

The `NotNull` methods (e.g. `Init`, `OnEntry`, etc.) are never called.

However, if I place the `[NotNull]` attribute directly on the method in the _class_ implementation (see below), the methods are called as expected.

```csharp
public interface ITestMe
{
   Task DoSomething();
}

public class TestMe : ITestMe
{
   [NotNull]
   public async Task DoSomething() 
   {
      // do something
   }
}
```

Is there a way to have this attribute propagate/cascade down into the concrete implementations of the interface?  I want to have this on the interface to ensure that classes that implement the interface are all utilizing the attribute.

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
