### ISSUE TITLE
Icon, package url are broken

### ISSUE THREAD

**Issue by abatishchev** [Fody/MethodDecorator#121]
I found few broken links:

1. The latest [NuGet package](https://www.nuget.org/packages/MethodDecorator.Fody/1.0.2)  points to https://github.com/Fody/MethodDecorator.Fody while the actual url is https://github.com/Fody/MethodDecorator
2. [readme.md](https://github.com/Fody/MethodDecorator/blob/master/readme.md) points to [this image](https://camo.githubusercontent.com/f4c27a387606767967c164005f7af26428a00dd4/68747470733a2f2f7261772e6769746875622e636f6d2f466f64792f4d6574686f644465636f7261746f722f6d61737465722f49636f6e732f7061636b6167655f69636f6e2e706e67) which doesn't exist anymore

**Comment by ltrzesniewski** [comment]
Thanks, I've fixed the icon URL. The project URL looks [correct in the source code](https://github.com/Fody/MethodDecorator/blob/6273a8ac3fa7ba0858e2fe118fd9971517a3c426/MethodDecorator/MethodDecorator.csproj#L13) OTOH, I guess the package just needs a new version to be deployed, although I'm not sure if it's worth it if it's the only change.

**Comment by abatishchev** [comment]
Thanks! I don't think it's worth it, will be fixed once the new version is published one day.
