### ISSUE TITLE
Can't debug anymore after decorating.

### ISSUE THREAD

**Issue by cando** [Fody/MethodDecorator#14]
After decorating with MethodDecorator any method of a library,when i set a breakpoint and i try to debug I get an error in visual studio 2013 "Source Information Not Avaible"  "Source information is missing from the debug information" and i'm unable to debug my code.
What could be the problem?
Thanks in advance.

**Comment by negue** [comment]
@cando  how did you managed to get it working? Since you closed the issue at cecil, any workaround / example code how to get it working?

**Comment by SimonCropp** [comment]
closing this as stale. please raise a new issue if this is still a problem
