### ISSUE TITLE
I can't seem to catch exceptions thrown from an async method

### ISSUE THREAD

**Issue by robertbird** [Fody/MethodDecorator#15]
Hi There,

This looks like a great project and I was hoping to use it for managing exceptions in a mobile application. However, most of the methods need to be async and it when I decorate my async method (returning a task) it doesn't get caught by my attribute.

Have you seen this before, is it a supported scenario?

it's likely that I am just doing something wrong, so this is more of a question than an issue. 

Thanks for any help you can give me.

Rob

**Comment by robertbird** [comment]
Hi @alexeysuvorov ,

Thanks for the reply, sorry to take so long to respond. 

I will try to get you a code sample this week.

Thanks,
Rob

**Comment by valdetero** [comment]
What happens if you combine MethodDecorator and https://github.com/Fody/AsyncErrorHandler ?

**Comment by robertbird** [comment]
Hi @valdetero ,

Thanks for your comment, it's been a while since I looked at this and to be honest I didn't end up going with Fody in the end. 

I do remember looking at AsynErrorHandler and thinking that the two combined would be perfect, but when I looked in the code they work in completely different ways and I couldn't work it out for myself :) In fact I raised this issue at the time: https://github.com/Fody/AsyncErrorHandler/issues/8

Would love to know if someone else works this out but I will close this ticket for now.

Thanks Rob

**Comment by valdetero** [comment]
I tried incorporating them both and the IL they generate seems to work ok. I'll have to try it in real use and see what my stack traces look like.
