### ISSUE TITLE
Attach interceptor on all method in assembly/namespace.

### ISSUE THREAD

**Issue by corvath** [Fody/MethodDecorator#17]
Hi,

Would the ability to add feature to define interceptors at the assembly?
I would like to be able to automatically attach  interceptors  to all method in the library. (or only on defined namespace)
PostSharp contains a similar function. For Example:
[assembly: ExceptionAspect (AttributeTargetTypes ="OurApplication.Controllers. *")]
I think that this feature would increase the usefulness of this framework.

**Comment by warnat** [comment]
+1

**Comment by ryrychj** [comment]
+1

**Comment by Tybielee** [comment]
Is there any word on whether or not this is actively being worked on?

**Comment by SimonCropp** [comment]
@Tybielee i have never had a need to use this in a project, nor did i write the origiginal code. This project was being maintained by @alexeysuvorov but like many of us i suspect life and paid work got in the way. If you send a pr to fix this i am more than happy to qa it and push it to nuget

**Comment by Tybielee** [comment]
@SimonCropp Well as I am still learning this I doubt I'd be able to fix it ;) but I figured I'd ask since it was back in 2015.

**Comment by alansingfield** [comment]
Please see pull request [https://github.com/Fody/MethodDecorator/pull/45] for a solution.

**Comment by SimonCropp** [comment]
closing this as stale. please raise a new issue if this is still a problem
