### ISSUE TITLE
Add Flow Behavior to continue method flow using on exception

### ISSUE THREAD

**Issue by ziyasal** [Fody/MethodDecorator#19]

**Comment by ChaseFlorell** [comment]
Is this similar to https://github.com/Fody/MethodDecorator/issues/26? I ask because I too want to be able to adjust what happens on exception... for me, I just want to be able to prevent the `re-throw`.

**Comment by ziyasal** [comment]
hi @ChaseFlorell  I have implemented flow behaviour to set rethrow or continue but I haven't create a pull request for this. I'll do asap..

**Comment by ChaseFlorell** [comment]
oh, fantastic. I was messing around with it yesterday, but with limited time, I couldn't tackle it and figure out the mono.cecil stuff.

**Comment by ziyasal** [comment]
@ChaseFlorell  thank you, here is [implementation](https://github.com/ziyasal/MethodDecorator/commit/c5d6888957055907a0b6c3843e3c82c9b1846725) I think this is up to date version.

**Comment by ChaseFlorell** [comment]
looks good. So this would require the first constructor argument to be the FlowBehavior, correct?

**Comment by ziyasal** [comment]
hi @ChaseFlorell ;

You can see implementation [here](https://github.com/ziyasal/MethodDecorator/blob/flow-behavior/MethodDecoratorInterfaces/MethodDecoratorAttributeBase.cs)

here is sample;
```csharp
 public class Sample
    {
        [LogInterceptor(FlowBehavior.Continue)]
        public void DoSth()
        {
            //do something
            for (int i = 0; i < 20; i++)
            {
                if (i % 3 == 0)
                {
                    throw new Exception("I'm an exception");
                }
            }
        }
    }
```

**Comment by ChaseFlorell** [comment]
Yep. I totally get it. Can you submit a PR? Maybe... if they take it, they can get it up into nuget :)

**Comment by ChaseFlorell** [comment]
Also, maybe FlowBehavior should live in the MethodDecoratorInterfaces project... that way MethodDecoratorEx.Fody will know about it inherently.

**Comment by ChaseFlorell** [comment]
super weird behavior.

I've decompiled the dll, and took a look at the method.

When I set `FlowBehavior.RethrowException`

      try
      {
        // ISSUE: method reference
        // ISSUE: type reference
        MethodBase methodFromHandle2 = MethodBase.GetMethodFromHandle(__methodref (GetOutagesCommand.Execute), __typeref (GetOutagesCommand));
        LoggingInterceptorAttribute interceptorAttribute2 = (LoggingInterceptorAttribute) Activator.CreateInstance(typeof (LoggingInterceptorAttribute));
        object[] args2 = new object[1]
        {
          parameter
        };
        interceptorAttribute2.Init((object) this, methodFromHandle2, args2);
        interceptorAttribute2.OnEntry();
        try
        {
          // ISSUE: variable of a compiler-generated type
          GetOutagesCommand.\u003CExecute\u003Ed__0 stateMachine;
          // ISSUE: reference to a compiler-generated field
          stateMachine.\u003C\u003E4__this = this;
          // ISSUE: reference to a compiler-generated field
          stateMachine.parameter = parameter;
          // ISSUE: reference to a compiler-generated field
          stateMachine.\u003C\u003Et__builder = AsyncVoidMethodBuilder.Create();
          // ISSUE: reference to a compiler-generated field
          stateMachine.\u003C\u003E1__state = -1;
          // ISSUE: reference to a compiler-generated field
          stateMachine.\u003C\u003Et__builder.Start<GetOutagesCommand.\u003CExecute\u003Ed__0>(ref stateMachine);
          interceptorAttribute2.OnExit();
        }
        catch (Exception ex)
        {
          interceptorAttribute2.OnException(ex);
          throw;
        }
        interceptorAttribute1.OnExit();
      }
      catch (Exception ex)
      {
        interceptorAttribute1.OnException(ex);
        throw;
      }

When I set `FlowBehavior.Continue`

     try
      {
        // ISSUE: method reference
        // ISSUE: type reference
        MethodBase methodFromHandle2 = MethodBase.GetMethodFromHandle(__methodref (GetOutagesCommand.Execute), __typeref (GetOutagesCommand));
        LoggingInterceptorAttribute interceptorAttribute2 = (LoggingInterceptorAttribute) Activator.CreateInstance(typeof (LoggingInterceptorAttribute));
        object[] args2 = new object[1]
        {
          parameter
        };
        interceptorAttribute2.Init((object) this, methodFromHandle2, args2);
        interceptorAttribute2.OnEntry();
        try
        {
          // ISSUE: variable of a compiler-generated type
          GetOutagesCommand.\u003CExecute\u003Ed__0 stateMachine;
          // ISSUE: reference to a compiler-generated field
          stateMachine.\u003C\u003E4__this = this;
          // ISSUE: reference to a compiler-generated field
          stateMachine.parameter = parameter;
          // ISSUE: reference to a compiler-generated field
          stateMachine.\u003C\u003Et__builder = AsyncVoidMethodBuilder.Create();
          // ISSUE: reference to a compiler-generated field
          stateMachine.\u003C\u003E1__state = -1;
          // ISSUE: reference to a compiler-generated field
          stateMachine.\u003C\u003Et__builder.Start<GetOutagesCommand.\u003CExecute\u003Ed__0>(ref stateMachine);
          interceptorAttribute2.OnExit();
        }
        catch (Exception ex)
        {
          interceptorAttribute2.OnException(ex);
        }
        interceptorAttribute1.OnExit();
      }
      catch (Exception ex)
      {
        interceptorAttribute1.OnException(ex);
      }

And the method is simply

```csharp
[Log(FlowBehavior.Continue)]
public override void Execute(object parameter)
{
    throw new Exception("you should never see this");
}
```

And the exception is thrown, not swallowed when using `continue`. So bizarre.

**Comment by DamianReeves** [comment]
This never got merged did it?

**Comment by SimonCropp** [comment]
closing this as stale. please raise a new issue if this is still a problem
