### ISSUE TITLE
Interceptor Attribute in Class Library not Triggered 

### ISSUE THREAD

**Issue by rd-nrg** [Fody/MethodDecorator#198]
Hello,
If an interceptor attribute is created in a class library and then referenced and used in another project the interceptor attribute is not triggered.
Am I missing something here?
Best,
Rd.

**Comment by ltrzesniewski** [comment]
Did you register the attribute correctly in the target project?

(from the readme)
```C#
// Attribute should be "registered" by adding as module or assembly custom attribute
[module: Interceptor]
```

**Comment by rd-nrg** [comment]
Yes, I did resister the attribute in the target project.
Rd.

**Comment by SimonCropp** [comment]
@rd-nrg can you please re read the issue template and follow all the required steps https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by ahmedalejo** [comment]
Also complementing @ltrzesniewski´s suggestion, you should also make sure you install `MethodDecorator.Fody` in the target project.

**Comment by SimonCropp** [comment]
@rd-nrg please share a stand alone solution that reproduces this issue

**Comment by StefanoVuerich** [comment]
I'm experiencing the same issue.

I have a class implementing Attribute, IMethodDecorator in class library A.

In class library B I've referenced class library A.
In class library B i've got attribute [module: Interceptor].

The decorator(generated) code is created only if, event class library B references MethodDecorator.Fody.

Is that the corret way of using the decorator?

**Comment by ltrzesniewski** [comment]
@StefanoVuerich yes, you need to install Fody and MethodDecorator.Fody in all projects where you want to use the decorator, as Fody is needed to modify them.

**Comment by StefanoVuerich** [comment]
@ltrzesniewski why are you not using transitive dependency style?

**Comment by ltrzesniewski** [comment]
Because that's not something we want by default: if we enabled transitivity, Fody weaving would be run on all projects that reference a project that uses Fody. That would be heavyweight, and you usually want to be able to control the scope of the weaving precisely, as you may want different weavers in different projects for instance. You would also need a FodyWeavers.xml file in each project to configure Fody.

**Comment by StefanoVuerich** [comment]
@ltrzesniewski 
At the moment we are using PostSharp. 
I was looking for alternatives and find Fody a really good one, except for the fact all the projects that want to use an attribute must reference Fody and MethodDecorator.Fody.
With Postsharp we have PS dependency only in the project that declares the attributes.
For me it's ok to have a FodyWeavers.xml in each project to describe the scope of the weaving.
After the assembly has been scanned, Fody can be runned only on projects that contains Fody's attributes.
