### ISSUE TITLE
IMethodDecorator implementation with constructor argumant 

### ISSUE THREAD

**Issue by noamtcohen** [Fody/MethodDecorator#20]
Hi, in the merge from MethodDecoratorEx constructor arguments are ignored and a parameter less constructor must be supplied.

**Comment by alexeysuvorov** [comment]
Can you give me any example how do you want to use constructor parameters? And how IL code should find and pass values for .ctor parameters?

**Comment by ahmedalejo** [comment]
@alexeysuvorov i guess @noamtcohen  meant being able to having a decorator attribute with no default constructor so one could do the following:

```csharp
[Decorator("Name")]
void Login()
{
    ...
}
```
i stated something similar proposing a solution in this issue #21

**Comment by noamtcohen** [comment]
Hi, I what I meant was being able to pass arguments to the constructor like this:

    [Decorator("Name")]
    void Login()
    {
        ...
    }

So that the value "Name" would be available in the object without reflecting.
Thanks.

**Comment by ahmedalejo** [comment]
I overcomed this limitation by creating a base `System.Attribute` class implementing IMethodDecorator.  It gets all read/writable properties lazily via reflection. in the constructor 
```csharp

        this._properties = new Lazy<IEnumerable<PropertyInfo>>(()=>
              this.GetType()
                  .GetRuntimeProperties()
                  .Where(p => p.CanRead && p.CanWrite));
```

then in the ```Init(object instance, MethodBase method, object[] args)``` a update the current instance with the the one anotated on method

```csharp
public virtual void Init(object instance, MethodBase method, object[] args)
    {
        this.UpdateFromInstance(method);
        //
        this.MethodDescription = method.DeclaringType.Name + "." + method.Name;
    }

private void UpdateFromInstance(MethodBase method)
    {
        this.DecoratedMethod = method;
        var declaredAttribute = method.GetCustomAttribute(this.GetType());

        foreach (var property in this._properties)
            property.SetValue(this, property.GetValue(declaredAttribute));

    }
```
Note that this is necessary because MethodDecorator creates a new instance of your method decorating attribute, and doesn´t use the one returned by ```MethodBase .GetCustomAttribute(Type)```
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;

[module: MethodDecorator]
/// <summary>
/// <see cref="https://github.com/Fody/MethodDecorator"/>
/// <seealso cref="https://github.com/alexeysuvorov/MethodDecorator"/>
/// </summary>
public interface IMethodDecorator
{
    void Init(object instance, MethodBase method, object[] args);
    void OnEntry();
    void OnExit();
    void OnException(Exception exception);
}

[AttributeUsage(
    AttributeTargets.Module |
    AttributeTargets.Method | 
    AttributeTargets.Assembly | 
    AttributeTargets.Constructor )]
public class MethodDecoratorAttribute : Attribute, IMethodDecorator
{
    private Lazy<IEnumerable<PropertyInfo>> _properties;
    public MethodBase DecoratedMethod { get; private set; }

    public MethodDecoratorAttribute()
    {
        this._properties = new Lazy<IEnumerable<PropertyInfo>>(()=>
              this.GetType()
                  .GetRuntimeProperties()
                  .Where(p => p.CanRead && p.CanWrite));
    }

    public string MethodDescription { get; private set; }
    public virtual void Init(object instance, MethodBase method, object[] args)
    {
        this.UpdateFromInstance(method);
        //
        this.MethodDescription = method.DeclaringType.Name + "." + method.Name;
    }

    public virtual void OnEntry() { }

    public virtual void OnExit() { }

    public virtual void OnException(Exception exception) { }

    private void UpdateFromInstance(MethodBase method)
    {
        this.DecoratedMethod = method;
        var declaredAttribute = method.GetCustomAttribute(this.GetType());

        foreach (var property in this._properties.Value)
            property.SetValue(this, property.GetValue(declaredAttribute));

    }
}
```

**Comment by noamtcohen** [comment]
Thanks, I found a different way to solve my problem. It was almost 6 months ago but I appreciate you help.

**Comment by ahmedalejo** [comment]
@noamtcohen could you share your "way"
i did mine months ago as well, but since i temporarily [stopped using MethodDecorator](https://github.com/Fody/MethodDecorator/issues/21#issuecomment-172343496), i decided to share what i learnt.

**Comment by noamtcohen** [comment]
In the end I didn't use Fody. I don't remember the alternative I used. Sorry....

**Comment by SimonCropp** [comment]
closing this as stale. please raise a new issue if this is still a problem
