### ISSUE TITLE
"PM> Install-Package MethodDecorator.Fody" doesn´t work but "PM> Install-Package MethodDecoratorEx.Fody" does.

### ISSUE THREAD

**Issue by ahmedalejo** [Fody/MethodDecorator#21]
The nuget package **MethodDecorator.Fody** doesn´t work on compile, keeps complaining about the `IMethodDecorator` interface not being correct even after trying the folllowing:

``` csharp
public interface IMethodDecorator
{
    void Init(object instance, MethodBase method, object[] args);
    void OnEntry();
    void OnExit();
    void OnException(Exception exception);
}
```

and the older syntax

``` csharp
public interface IMethodDecorator
{
    void Init(object instance, MethodBase method, object[] args);
    void OnEntry(MethodBase method);
    void OnExit(MethodBase method);
    void OnException(MethodBase method, Exception exception);
}
```

I´ve tried defining the classes on root namespace and module register the attribute.

But got it working when i used the **MethodDecoratorEx.Fody** package instead:

``` csharp
[assembly: MethodDecorator]

public interface IMethodDecorator
{
    void Init(object instance, MethodBase method, object[] args);
    void OnEntry();
    void OnExit();
    void OnException(Exception exception);
}
```

I guess the `MethodDecoratorEx.Fody` package has to be updated

**Now the real problem**
I would like to open an issue/contribute on it´s fork @alexeysuvorov fork ( i.e **MethodDecoratorEx.Fody**) but it seems not to allow this.

I know post sharp(and it´s price), but being a big Python(decorators) fan but a .NET developer i´ve always wanted C# to have such capabilities without the overly complex CQRS ICommandHandler pattern well explained by "Famous" [Steven](https://stackoverflow.com/users/264697/steven)

**Comment by SimonCropp** [comment]
so @alexeysuvorov since u r now an owner of this project can we merge MethodDecoratorEx and MethodDecoratorEx  ?

**Comment by alexeysuvorov** [comment]
@SimonCropp I suppose you mean merge from MethodDecoratorEx to MethodDecorator. It was merged in April 2015. But unfortunately I cannot help with nuget because I don't own it. If you don't mind can you add me as owner/contributor to nuget package also or just update it yourself by compiling sources from repo.

**Comment by SimonCropp** [comment]
@alexeysuvorov u r x0040h  on nuget? it says u have a pending approval

**Comment by alexeysuvorov** [comment]
@SimonCropp yes, that is me, but I cannot find any link to approve this action. Can you please re-add me, maybe I will receive notification this time. Thanks.

**Comment by SimonCropp** [comment]
@alexeysuvorov  re added.

**Comment by SimonCropp** [comment]
@alexeysuvorov try logging in and going here https://www.nuget.org/account  i think pending access are shown there

**Comment by ahmedalejo** [comment]
@alexeysuvorov great to hear from you.
I saw that it was merged and only the nuget package was out dated.

I had proposals(mostly as pull requests)  i´d like to contribute:
Given a decorator named DecoratorAttribute

1) Make the weaver to use the attribute instance as declared on method
    instead of using the following
```csharp
DecoratorAttribute decoratorAttribute = (DecoratorAttribute)Activator.CreateInstance(typeof(DecoratorAttribute));
```
Then allowing to do this.

```csharp
[Decorator("Important")]
void Decoratee()
{
     ...
}
```

There might be an issue with the ```MethodDecorator.Init(...)``` due to multithreading

2) Possibility to handle exception without throwing:

```csharp
catch (Exception exception)
{
    if(!decoratorAttribute.OnException(exception));
       throw;
}
```

3) A *Finally* method
```csharp
finally
{
     decoratorAttribute.Finally();
}
```

4) Possibility to capture method return value(if any). and provide return value without calling actual 
    method. How this could be implemented should be debated.

we could do the following:

```csharp
[ReportsDuration(LongerThan=TimeSpan.FromSeconds(5))]
async protected Task<bool> Login()
{
	MethodBase methodFromHandle = MethodBase.GetMethodFromHandle(methodof(LoginViewModel.Login()).MethodHandle, typeof(LoginViewModel).TypeHandle);

	ReportsDurationAttribute trackTimeAttribute= (ReportsDurationAttribute )methodFromHandle .GetCustomAttribute(typeof(ReportsDuration));
	object[] args = new object[0];
	reportsDurationAttribute .Init(this, methodFromHandle, args);

	if(!trackTimeAttribute.OnEntry()) //if shouldn´t enter.
		return (bool)trackTimeAttribute.OnExit(); //if method is void simply return(ignoring the on exit return value)

	trackTimeAttribute.OnEntry();
	bool result;
	try
	{
		bool Login= await this.AuthService(this.user, this.password)
		bool flag = Login;
		result = flag;
		trackTimeAttribute.OnExit(result);
	}
	catch (Exception exception)
	{
		if(!trackTimeAttribute.OnException(exception)) // if not handled
		    throw;
	}
	finally
	{
		reportsDurationAttribute.Finally();
	}
	return result;
}
```
instead of

```csharp
public class ReportsSlowExecutionAttribute : ReportsDurationAttribute
{
	public ReportsSlowExecutionAttribute ()
                 :base(TimeSpan.FromSeconds(5)){}
}
[ReportsSlowExecution ]
async protected Task<bool> Login()
{
	MethodBase methodFromHandle = MethodBase.GetMethodFromHandle(methodof(LoginViewModel.Login()).MethodHandle, typeof(LoginViewModel).TypeHandle);

	ReportsDurationAttribute reportsDurationAttribute = (ReportsDurationAttribute)Activator.CreateInstance(typeof(ReportsDurationAttribute));

	object[] args = new object[0];
	reportsDurationAttribute .Init(this, methodFromHandle, args);
	reportsDurationAttribute .OnEntry();
	bool result;
	try
	{
		bool Login= await this.AuthService(this.user, this.password)
		bool flag = Login;
		result = flag;
		reportsDurationAttribute .OnExit();
	}
	catch (Exception exception)
	{
		reportsDurationAttribute.OnException(exception);
		throw;
	}
	finally
	{
		reportsDurationAttribute.Finally();
	}
	return result;
}
```

With the following onestop interface:
```csharp
public interface IMethodDecorator
{
    void Init(object instance, MethodBase method, object[] args);
    bool OnEntry();
    object OnExit();
    void OnExit(object returnValue);
    bool OnException(Exception exception);
    void Finally();
}
```
or two interfaces, one for void methods and another for non-void
```csharp
public interface INonVoidMethodDecorator
{
    void Init(object instance, MethodBase method, object[] args);
    bool OnEntry();
    object OnExit()
    void OnExit(object returnValue);
    bool OnException(Exception exception);
    void Finally();
}

public interface IMethodDecorator
{
    void Init(object instance, MethodBase method, object[] args);
    bool OnEntry();
    void OnExit();
    bool OnException(Exception exception);
    void Finally();
}
```
Given that 2 and 3 are implemented(i.e foundation functionalities) the sky would be the limit in 
creating utility decorators like

1. MethodCache.Fody
2. MethodTimer.Fody
3. NullGuard.Fody
and many others

This would make MethodDecorator.Fody a de-facto option for creating decorators. without having to
handle the nifty details of Fody´s moduleweaver.

Thanks a lot @SimonCropp for the follow up.

**Comment by ahmedalejo** [comment]
Bump @SimonCropp

**Comment by SimonCropp** [comment]
@ahmedalejo you are bumping the wrong person. u need to ping @alexeysuvorov  :)

**Comment by alexeysuvorov** [comment]
Hello @ahmedalejo, I think that adding optional constructor argument is good. I will do it once I have time, or if you have code to doing so please create a pull request.
But I am not sure about making OnException returns bool to make exception handled because it can confuse user. @SimonCropp how do you think?

**Comment by SimonCropp** [comment]
@ahmedalejo can u give some more details as to why OnException  should return a bool. is it so as to re throw and not give a misleading stack trace?

**Comment by ahmedalejo** [comment]
Sorry @SimonCropp 

I actually wanted to be able to suppress exceptions. i.e handling them without propagating.

do OnException could return a true indicating the exception was handled(method returns if  void  or default(ReturnValue type if non-void ))

**Comment by SimonCropp** [comment]
perhaps i am overthinking it... but returning bool seems a confusing API. would prefer an out bool. or pass in a context that they can call a method on. but i will defer to @alexeysuvorov

**Comment by ahmedalejo** [comment]
I don´t have problem with this, it would be cool to do this. i.e method call bypassing and exception handling

**Comment by benbenbenbenbenben** [comment]
@ahmedalejo did anything happen regarding the return value intercepting? This is kind of just what I'm looking for right now - for a conditional caching weaver.

I might take a look this weekend if nothing has happened.

**Comment by ahmedalejo** [comment]
@benbenbenbenbenben Nothing happened, i actually no longer use it, i had to drop **MethodDecorator** after some drawbacks with my xamarin(forms) build system, 
3) file hangs, slower builds,
2) incomplete(for me) functionality, (need to cut down external dependencies.. even though Method)
1) The need to reference MethodDecoratorInterfaces.dll by hand in my Xamarin.Android projects(i should have reported this). This was maybe the number one reason for dropping it.(But i think it´s a very xamarin specific reason though)

Anyways, since i don´t have a blog(which i´m desperately in need of, for sharing awesome code i came up with) i´d like to share what i did to resolve some issues.

#20 **IMethodDecorator implementation with constructor argumant**

I overcomed this limitation by creating a base ```System.Attribute``` class implementing IMethodDecorator.  It gets all read/writable properties lazily via reflection. in the constructor 
```csharp

        this._properties = new Lazy<IEnumerable<PropertyInfo>>(()=>
              this.GetType()
                  .GetRuntimeProperties()
                  .Where(p => p.CanRead && p.CanWrite));
```

then in the ```Init(object instance, MethodBase method, object[] args)``` a update the current instance with the the one anotated on method

```csharp
public virtual void Init(object instance, MethodBase method, object[] args)
    {
        this.UpdateFromInstance(method);
        //
        this.MethodDescription = method.DeclaringType.Name + "." + method.Name;
    }

private void UpdateFromInstance(MethodBase method)
    {
        this.DecoratedMethod = method;
        var declaredAttribute = method.GetCustomAttribute(this.GetType());

        foreach (var property in this._properties)
            property.SetValue(this, property.GetValue(declaredAttribute));

    }
```
Note that this is necessary because MethodDecorator creates a new instance of your method decorating attribute, and doesn´t use the one returned by ```MethodBase .GetCustomAttribute(Type)```

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;

[module: MethodDecorator]
/// <summary>
/// <see cref="https://github.com/Fody/MethodDecorator"/>
/// <seealso cref="https://github.com/alexeysuvorov/MethodDecorator"/>
/// </summary>
public interface IMethodDecorator
{
    void Init(object instance, MethodBase method, object[] args);
    void OnEntry();
    void OnExit();
    void OnException(Exception exception);
}

[AttributeUsage(
    AttributeTargets.Module |
    AttributeTargets.Method | 
    AttributeTargets.Assembly | 
    AttributeTargets.Constructor )]
public class MethodDecoratorAttribute : Attribute, IMethodDecorator
{
    private Lazy<IEnumerable<PropertyInfo>> _properties;
    public MethodBase DecoratedMethod { get; private set; }

    public MethodDecoratorAttribute()
    {
        this._properties = new Lazy<IEnumerable<PropertyInfo>>(()=>
              this.GetType()
                  .GetRuntimeProperties()
                  .Where(p => p.CanRead && p.CanWrite));
    }

    public string MethodDescription { get; private set; }
    public virtual void Init(object instance, MethodBase method, object[] args)
    {
        this.UpdateFromInstance(method);
        //
        this.MethodDescription = method.DeclaringType.Name + "." + method.Name;
    }

    public virtual void OnEntry() { }

    public virtual void OnExit() { }

    public virtual void OnException(Exception exception) { }

    private void UpdateFromInstance(MethodBase method)
    {
        this.DecoratedMethod = method;
        var declaredAttribute = method.GetCustomAttribute(this.GetType());

        foreach (var property in this._properties.Value)
            property.SetValue(this, property.GetValue(declaredAttribute));

    }
}
```

#for those that use **Xamarin.Insights**, Here is a mouth watering solution:

1. `ReportEventAttribute` -> Calls Xamarin.Insights.Track(...) if Insights is initialized
```csharp
[ReportEvent("LoginAsync")] // or simply [ReportEvent] to use method name
async Task<bool> LoginAsync()
{
    ...
}
```

2. `ReportDurationAttribute` -> Calls Xamarin.TrackTime(...) if Insights is initialized on method call start and only disposes on end if the duration was greater than ReportDurationAttribute.LongerThan which defaults to 0 milliseconds
```csharp
[ReportDuration("LoginAsync", LongerThan = 1000)] 
// or simply [ReportDuration(1000)] to use method name
async Task<bool> LoginAsync()
{
    ...
}
```

3. `ReportSlowExecutionAttribute` -> Calls Xamarin.TrackTime(...) if Insights is initialized on method call start and only disposes on end if the duration was longer than ReportSlowExecutionAttribute.LongerThan which defaults to 1000 * 5 milliseconds(5 seconds)
```csharp
[ReportSlowExecution("LoginAsync", LongerThan = Duration.FiveSeconds)] 
// or [ReportDuration(Duration.FiveSeconds)] 
async Task<bool> LoginAsync()
{
    ...
}
```

The complete code follows:

```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics;
using Xamarin;

namespace Shared.Core.Analytics
{
	using Common;

    public class ReportEventAttribute : InsightsAttribute
    {
        public ReportEventAttribute() { }
        public ReportEventAttribute(string Description): base(Description){ }
        public override void HandleEntry() { this.Track(); }
        public override void HandleExit() {  }
    }

    public class ReportDurationAttribute : InsightsAttribute
    {
        public ReportDurationAttribute() { }
        public ReportDurationAttribute(string Description): base(Description){ }
        public ReportDurationAttribute(double LongerThan)
        {
            this.LongerThan = LongerThan;
        }

        private IDisposable _trackerDisposable;
        private Stopwatch _watch;
        
        public double LongerThan { get; set; }

        public override void HandleEntry()
        {
            this._watch = Stopwatch.StartNew();

            var detail = this.LongerThan > 0 
                ? new Dictionary<string, string> { { "Message", "Operation took longer than " + TimeSpan.FromMilliseconds(this.LongerThan) } }
                : null;
            
            this._trackerDisposable = this.TrackTime(extraData: detail);
        }

        public override void HandleExit()
        {
            if (this._watch.ElapsedMilliseconds > LongerThan)
                this._trackerDisposable.Dispose();
        }
    }

    /// <summary>
    /// Defaults to reporting method/constructor execution time greater than <see cref="Duration.FiveSeconds"/>
    /// in milliseconds 
    /// </summary>
    public class ReportSlowExecution : ReportDurationAttribute
    {
        public ReportSlowExecution()
        {
            this.LongerThan = Duration.FiveSeconds;
        }
        public ReportSlowExecution(string Description): base(Description){ }
    }

	public abstract class InsightsAttribute : MethodDecoratorAttribute
    {
        public InsightsAttribute() { }
        public InsightsAttribute(string Description)
        {
            this._description = Description;
        }

        private string _description;
        public string Description
        {
            get { return this._description ?? this.MethodDescription; }
            set { this._description = value; }
        }

        public override void OnEntry()
        {
            if (!Insights.IsInitialized)
                return;

            this.HandleEntry();
        }

        public abstract void HandleEntry();

        public override void OnExit()
        {
            if (!Insights.IsInitialized)
                return;

            this.HandleExit();
        }

        public abstract void HandleExit();

        public override void OnException(Exception exception)
        {
            if (!Insights.IsInitialized)
                return;

            this.HandleException(exception);
        }

        public virtual void HandleException(Exception exception)
        {
            this.Track(identifier: this.Description + "- Error");

            Insights.Report(exception, value: this.Description);
        }

        public virtual void Track(string identifier = null, IDictionary<string, object> extraData = null)
        {
            Insights.Track(identifier ?? this.Description, table: extraData);
        }

        public virtual IDisposable TrackTime(string identifier = null, IDictionary<string, string> extraData = null)
        {
            return Insights.TrackTime(identifier ?? this.Description, table: extraData);
        }
    }

/// <summary>
    /// Millisecond based durations
    /// </summary>
    public static class Duration
    {
        public const double OneSecond = 1000;
        public const double FiveSeconds = OneSecond * 5;
        public const double OneMinute = OneSecond * 60;
    }
}
```
  
This could as well be a Xamarin.Insights Extension or MethodDecoratorEx Extension :) packages

**Comment by benbenbenbenbenben** [comment]
Thanks for the info @ahmedalejo, I'll keep an eye out for something easier. I don't have a lot of time see. I did use postsharp when I wanted to do this sort of thing before but I'm trying to find an open source alternative.

**Comment by SimonCropp** [comment]
closing this as stale. please raise a new issue if this is still a problem
