### ISSUE TITLE
Decide whether to rethrow exception

### ISSUE THREAD

**Issue by GioviQ** [Fody/MethodDecorator#224]
Where it is clear that the below content has not read, the issue is likely to be closed with "please read the template". Please don't take offense at this. It is simply a time management decision. When someone raises an issue, without reading the template, then often too much time is spent going back and forth to obtain information that is outlined below.

#### You should already be a Patron

At the moment I am not a member of Patron. I have to decide if use Fody or something else. 

#### Is the proposal related to a problem

Here https://github.com/Fody/MethodDecorator#what-gets-compiled
I see that implementation does not consent to decide whether to rethrow exception.

Also looking at https://github.com/Fody/FodyAddinSamples/tree/master/MethodDecoratorSample
this repository is not used. This is propably a newbie question...

**Comment by gmkado** [comment]
@GioviQ FYI MethodBoundaryAspect can do this with FlowBehavior https://github.com/vescon/MethodBoundaryAspect.Fody

```
using MethodBoundaryAspect.Fody.Attributes;
public sealed class MessageBoxOnErrorAttribute : OnMethodBoundaryAspect
{
    
    public override void OnException(MethodExecutionArgs arg)
    {
        arg.FlowBehavior = FlowBehavior.Return;
    }
}
```

**Comment by GioviQ** [comment]
@gmkado Thanks
