### ISSUE TITLE
Which nupkg should we be using?

### ISSUE THREAD

**Issue by ChaseFlorell** [Fody/MethodDecorator#24]
I'm seeing two different nuget packages `MethodDecorator.Fody` and `MethodDecoratorEx.Fody`. I see from another issue there was chatter about merging the two, but I also see that the `Ex` version is more recent on Nuget. I'm just wondering which version is the current one, and, should the other one be deprecated?

**Comment by alexeysuvorov** [comment]
Hi, currently I support method decorator. Latest and most up to date version is in ex package. Unfortunately I don't have access to method decorator.fody and cannot update it.

**Comment by ChaseFlorell** [comment]
@alexeysuvorov it looks like the project was offered to you back in 2014

https://github.com/Fody/MethodDecorator/issues/10#issuecomment-60480885

**Comment by SimonCropp** [comment]
@ChaseFlorell this is not @alexeysuvorov fault. we tried to grant him access but nuget would not work for us. I have raised an issue on nuget gallery https://github.com/NuGet/NuGetGallery/issues/2778

**Comment by ChaseFlorell** [comment]
oh interesting. Yeah I wasn't blaming him, thought he might have missed it.

**Comment by SimonCropp** [comment]
@alexeysuvorov  seems the nuget guys fixed this. so i will close this. please re-open if u still have issues
