### ISSUE TITLE
Ability to decorate all methods in project

### ISSUE THREAD

**Issue by DamirAinullin** [Fody/MethodDecorator#241]
Is possible to decorate all methods in project using MethodDecorator? It is not I think it would be the great feature. I want to wrap all methods for all classes in the project and I don't want to add attrbute for every method of every class. Can you help me please with this problem?

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
