### ISSUE TITLE
Could not load assembly "MethodDecoratorInterfaces"

### ISSUE THREAD

**Issue by ChaseFlorell** [Fody/MethodDecorator#25]
I've installed Fody and MethodDecoratorEx into my PCL (only), and I've created an IMethodDecorated (without a namespace) inside the same PCL. *I have not installed either of the two packages in any other project*.

```csharp
using System;
using System.Reflection;

// ReSharper disable once CheckNamespace
// intentionally not in a namespace.
public interface IMethodDecorator
{
    void Init(object instance, MethodBase method, object[] args);
    void OnEntry();
    void OnExit();
    void OnException(Exception exception);
}
```

I've created an interceptor implementing it.

```csharp
using System;
using System.Diagnostics;
using System.Reflection;
using MyApp.Core.Logging;

[module: LoggingInterceptor]

namespace MyApp.Core.Logging
{
    [AttributeUsage(AttributeTargets.Method | AttributeTargets.Constructor | AttributeTargets.Assembly | AttributeTargets.Module)]
    public class LoggingInterceptor : Attribute, IMethodDecorator
    {
        public LoggingInterceptor() { }

        public void Init(object instance, MethodBase method, object[] args)
        {
            Debug.WriteLine("Entering Method");
        }

        public void OnEntry()
        {
            Debug.WriteLine("Starting Method");
        }

        public void OnExit()
        {
            Debug.WriteLine("Exiting Method");
        }

        public void OnException(Exception exception)
        {
            Debug.WriteLine("Exception was thrown");
        }
    }
}
```

and I've decorated a class inside my PCL with the interceptor.

The issue I've run into is that when I try and deploy my android app (that uses the pcl), I get the following error.

> Error	7	Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'MethodDecoratorInterfaces, Version=0.9.0.4, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'MethodDecoratorInterfaces.dll'
   at Xamarin.Android.Tuner.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute()	MyApp.Droid

Is this a bug in MethodDecorator, or am I missing something in my code? Am I supposed to also install Fody in my Droid project? If so, I get another error that I don't have any registered weavers. I ***CAN*** build the PCL on it's own, it's only when I try and deploy the droid app that the error shows up.

note: it [appears as though I'm not the only one](http://streamofconsciousness.davidbarrett.net/2014/05/07/aop-in-xamarin/comment-page-1/#comment-70)

**Comment by icnocop** [comment]
For reference, I converted MethodDecoratorInterfaces.csproj to PCL as part of PR https://github.com/Fody/MethodDecorator/pull/64.
