### ISSUE TITLE
Flag to prevent rethrow

### ISSUE THREAD

**Issue by ChaseFlorell** [Fody/MethodDecorator#26]
What is the appetite to adding a flag that prevents the re-throw of the exception in OnException? I'd like to be able to keep my application alive in the case of an error.

If I wrap potentially volatile code in a `try/catch`, then decorate the outer method with my Interceptor, the OnError never triggers because the try/catch caught it. I'd like to have a logger log the error, but keep the app up.

Essentially the bit in the readme that says

```
    catch (Exception exception) {
        attribute.OnException(exception);
        throw;
    }
```

would have something like

```
    catch (Exception exception) {
        attribute.OnException(exception);
        if(!ContinueOnException)
            throw;
    }
```

**Comment by ChaseFlorell** [comment]
Not sure if @@alexeysuvorov follows this thread, so... tagging.

**Comment by SimonCropp** [comment]
@alexeysuvorov any thoughts on this ?

**Comment by SimonCropp** [comment]
closing this as stale. please raise a new issue if this is still a problem

**Comment by wcfCode** [comment]
This does not work. Thank you.
