### ISSUE TITLE
Change parameters

### ISSUE THREAD

**Issue by ProESM** [Fody/MethodDecorator#29]
Можно ли изменить значения параметров из args?

Допустим, пользователь прислал определенный заполненный список параметров, но мне необходимо при возникновении ошибки в базовом методе, переопределить некоторые значения и запустить метод еще раз.

Заранее спасибо!

**Comment by ProESM** [comment]
Я пробовал сделать так:
<code>		private object _instance;
		private MethodBase _method;
		private object[] _baseMethodArgs;

		// instance, method and args can be captured here and stored in attribute instance fields
		// for future usage in OnEntry/OnExit/OnException
		public void Init(object instance, MethodBase method, object[] args)
		{
			_instance = instance;
			_method = method;
			_baseMethodArgs = args;
		}</code>
Далее вызывал:
<code>
_baseMethodArgs[0] = value;
_method.Invoke(_instance, _baseMethodArgs);
</code>

Но получаю ошибку:
Выдано исключение типа "System.StackOverflowException".

**Comment by ProESM** [comment]
Извиняюсь. Все норм. Просто я неверно вызвал _method.Invoke в OnEntry.
Вызвал в OnException и все норм :-)

**Comment by alexeysuvorov** [comment]
Happy you figured out this )
