### ISSUE TITLE
Playing nice with async exceptions

### ISSUE THREAD

**Issue by swestner** [Fody/MethodDecorator#30]
It would be great if method decorators would play nice with async exceptions. What would be involved in making this happen? 

Looking at the AsyncErrorHandler repo, it walks the instruction stack and looks for the SetException methods and injects prior to that. Would that approach be valid here? Or is there something obvious I am overlooking?

**Comment by Tybielee** [comment]
@swestner were you able to get the MethodDecorator to play nicely with asynchronous methods in general? I'm having issues with the accuracy of the OnExit method being called well before the method itself has finished.

**Comment by icnocop** [comment]
Why not just use AsyncErrorHandler?

**Comment by SimonCropp** [comment]
closing this as stale. please raise a new issue if this is still a problem
