### ISSUE TITLE
Init method not invoked

### ISSUE THREAD

**Issue by azrael1111** [Fody/MethodDecorator#31]
I have implemented everything best to my knowledge **IMethodDecorator** outside of a namespace. The version is 0.8.1.1.

```
public interface IMethodDecorator
{
    void Init(object instance, MethodBase method, object[] args);
    void OnEntry(MethodBase method);
    void OnExit(MethodBase method);
    void OnException(MethodBase method, Exception exception);
}
```

The interceptor

```
[AttributeUsage(AttributeTargets.Method | AttributeTargets.Constructor | AttributeTargets.Module)]
public class InterceptorAttribute : Attribute, IMethodDecorator
{

    public void Init(object instance, MethodBase method, object[] args)
    {

    }

    public void OnEntry(MethodBase method)
    {
        //called on enter
    }
    public void OnExit(MethodBase method)
    {
        //called on exit
    }
    public void OnException(MethodBase method, Exception exception)
    {
        // called if exception happens
    }
}
```

and added [module:Interceptor] to the AssemblyInfo.cs

The result is, that The OnEntry, and OnExit methods get executed, But the Init method never does.

Any suggestions how.

**Comment by azrael1111** [comment]
Anyone? .... maybeeee?

**Comment by Tybielee** [comment]
@azrael1111 Is your attribute in the same project as the methods you are trying to execute this on? I'm currently trying to implement this and none of the methods are being executed.

**Comment by Tybielee** [comment]
So I was able to resolve my problem and the Init function does get executed. Maybe if you update to 0.9 this will help you. The only difference so far I can tell between my IMethodDecorator and yours is that with mine and with 0.9 it looks like this
'
    public interface IMethodDecorator
    {
        void Init(object instance, MethodBase method, object[] args);
        void OnEntry();
        void OnExit();
        void OnException(Exception exception);
    }
'

**Comment by SimonCropp** [comment]
closing this as stale. please raise a new issue if this is still a problem
