### ISSUE TITLE
NuGet package for MethodDecoratorEx not installing

### ISSUE THREAD

**Issue by Tybielee** [Fody/MethodDecorator#33]
I have been trying to install the MethodDecoratorEx through Nuget to no avail. I'm am not sure if this is expected but when I install the package, The FodyWeavers.xml and packages.config are added as I had neither prior to installing. However, neither the dependency Fody or the MethodDecoratorEx itself show up in my references. Is this expected or am I simply doing something wrong? I should note that I have used MethodTimer in the past and the dependency Fody doesn't appear when I install that package either but MethodTimer itself shows up in my references.
Thanks

**Comment by Tybielee** [comment]
I was able to get this to work by looking at other issues and seeing peoples code they posted. It would be nice if there was a more user-friendly readme on getting started with this particular add-in. That specifically states you need to add the interface in your own code.

**Comment by SimonCropp** [comment]
@Tybielee "It would be nice if there was a more user-friendly readme on getting started with this particular add-in. That specifically states you need to add the interface in your own code." 

Sounds good. Do u want to have a go at creating it?

**Comment by Tybielee** [comment]
@SimonCropp I am still learning the project itself. I will definitely keep notes of what I am doing as people in my workplace will also need to understand this. Unless someone else can do it faster than me I can work on creating it as I learn the project if that isn't an issue.
