### ISSUE TITLE
Asynchronous methods calling OnExit too Early

### ISSUE THREAD

**Issue by Tybielee** [Fody/MethodDecorator#35]
I was doing a simple test that uses both MethodTimer fody package and the MethodDecorator to hopefully achieve something I require. However, when simply testing the project out with Console.Write("OnExit"); in the OnExit method, it seems to be printed far sooner than one expects for an asynchronous method. I know that the asynchronous method itself has not yet finished because the MethodTimer is measuring the execution time and that doesn't output to the console until a few seconds later. 
Am I missing something as to what kinds of async are allowed? Or can anyone point me in the right direction of getting asynchronous methods to work?

**Comment by FrancoisM** [comment]
It seems to work for me.
However if your target async method throw an exception then OnExit is called (but not OnException which doesn't catch async exceptions) and this is surely what you see.

**Comment by Tybielee** [comment]
Hi, regardless of the fact that it may work for some and it may work for others, when wanting to time methods that are decorated, you will be unable to get a proper time. The instructions also fail to mention for asynchronous methods you are required to implement OnTaskContinuation which is how I was able to get asynchronous methods actually properly working. This is because if you are doing any sort of finishing tasks in the OnExit this method gets called even before the asynchronous method finishes. I am going to close this as I have gotten it working for my purposes but it is similar to the issue of [https://github.com/Fody/MethodDecorator/issues/28](url)

**Comment by Tybielee** [comment]
#28

**Comment by FrancoisM** [comment]
I didn't manage to make any use of OnTaskContinuation. Unhandled Exceptions appears before I can see the exception in OnTaskContinuation.
I think I'll revert to interface decortors...
