### ISSUE TITLE
How about `Attribute.GetCustomAttributes()` performance?

### ISSUE THREAD

**Issue by jerviscui** [Fody/MethodDecorator#366]
I check the created code.
I see the under code will added in target method front,

```csharp
MethodBase methodFromHandle = MethodBase.GetMethodFromHandle((RuntimeMethodHandle)/*OpCode not supported: LdMemberToken*/, typeof(Test).TypeHandle);
		Attribute[] customAttributes = Attribute.GetCustomAttributes(methodFromHandle, typeof(LogAttribute));
```

I want to know how about `MethodBase.GetMethodFromHandle()` and `Attribute.GetCustomAttributes()` methods performance.

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by tom-englert** [comment]
@jerviscui try something like this : https://github.com/dotnet/BenchmarkDotNet

**Comment by jerviscui** [comment]
@SimonCropp  OK, thank you.

If I can, I will be a patron of Fody.
