### ISSUE TITLE
Ability to control throwing exception

### ISSUE THREAD

**Issue by Bakanych** [Fody/MethodDecorator#372]
Hello!
I tried to use this module to implement global test retry mechanism for the test framework.
The idea is to intercept test method exceptions and retry them from `OnException` doing something like:
```
    public void OnException(Exception exception)
    {
      int callCount = new StackTrace().GetFrames().Count(x => x.GetMethod() == this.method);
      if (callCount < this.retryCount)
          this.method.Invoke(this.instance, this.args);
      else
          throw exception;
     }
```
The problem is caught exception will be thrown anyway after calling `OnException` as per readme:
```
  catch (Exception exception) {
            attribute.OnException(exception);
            throw;
        }
```

Can we make throwing exception after calling  `OnException` configurable with current behavior as default, e.g.
```
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
    <MethodDecorator RethrowExceptions="true" />
</Weavers>
```

I honestly tried to fix it by myself in the fork, but my knowledge of MSIL is far behind :(

Any help appreciated.

Thanks!

**Comment by SimonCropp** [comment]
can u ensure you have followed the issue template https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Bakanych** [comment]
I believe I followed the guide described in the template by providing problem description also as described the solution.
Please let me know how can I fix it to follow all the standards.

Thank you!

**Comment by SimonCropp** [comment]
so you and all devs using fody in your company a patrons of the Fody open collective? https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/feature_proposal.md#you-should-already-be-a-patron
