### ISSUE TITLE
Add an interceptor type that wraps the method execution

### ISSUE THREAD

**Issue by emisand** [Fody/MethodDecorator#378]
Currently this Fody addin allows us to intercept a method On Entry, On Exit or On Exception.

I've worked with PostSharp in the past, and they have their [MethodInterceptionAspect](https://doc.postsharp.net/method-interception) where you can wrap the entire method execution, and Invoke the original method contents by calling to the `Proceed` or `ProceedAsync` methods when desired, or not call it at all in order to completely skip the original method execution. The latter option that would allow us to skip the original method execution is not possible with the boundaries defined in this addin, unless we throw an exception inside the `OnEntry` method.

So my proposed feature is to add another method interception type with two virtual/abstract methods called `OnInvoke` and `OnInvokeAsync`, both receiving a context parameter with the `Proceed` and `ProceedAsync` methods. The context parameter should also have a return value property that will be automatically loaded after the Proceed method completes.

I understand this may take several hours to develop, and even being a patron right now, I am willing to make an additional donation for this development to be done if it's approved.

**Comment by SimonCropp** [comment]
unfortunately i dont have capacity to work on this. Happy to consider a PR if anyone else does

**Comment by matkoch** [comment]
For everyone else coming here, check out https://github.com/ArxOne/MrAdvice
