### ISSUE TITLE
Get exception if mscorlib 2.0.0.0 AND 4.0.0.0 is referenced in target assembly

### ISSUE THREAD

**Issue by chrisbehle** [Fody/MethodDecorator#38]
My target assembly references libraries which are targeting different version of the CLR (.NET 2 CLR or .NET 4 CLR). This results in multiple references to mscorlib. 
The  `Execute()` method of the weaver throws an exception if the reference count is greater 1. The [RemoveReference](https://github.com/icnocop/RemoveReference.Fody)-Weaver doesn't help here, because after compiling the application won't start.

**Comment by SimonCropp** [comment]
Can u upload a repro
