### ISSUE TITLE
Should have method arguments

### ISSUE THREAD

**Issue by ramyhhh** [Fody/MethodDecorator#4]
The methods "before" and "after" have MethodInfo parameters which helps with getting the name and signature of the original method but also original method arguments are important so could you improve this cool plugin to read original method parameters.
Thanks

**Comment by SimonCropp** [comment]
@alexeysuvorov any update on this?

**Comment by alexeysuvorov** [comment]
Just merged my repository to MethodDecorator. Not sure I can publish nuget package.

**Comment by SimonCropp** [comment]
@alexeysuvorov what is your nuget name?

**Comment by alexeysuvorov** [comment]
Id is MethodDecoratorEx.Fody
https://www.nuget.org/packages/MethodDecoratorEx.Fody/

**Comment by noamtcohen** [comment]
@alexeysuvorov I've install this package but I'm getting this error:
```Fody: Could not find type 'IMethodDecorator' or 'MethodDecoratorAttribute'```

**Comment by noamtcohen** [comment]
@alexeysuvorov I got this to compile by removed the MethodDecorator package and manually referencing the dlls from the MethodDecoratorEx package folder. Now I get this runtime exception:
```System.InvalidProgramException : Common Language Runtime detected an invalid program.```

**Comment by noamtcohen** [comment]
After removing the old Methods (and not having them mixed with the Ex methods together):
```csharp
public void OnEntry(MethodBase method){}
public void OnExit(MethodBase method){}
public void OnException(MethodBase method, Exception exception){}
```
And added a parameterless constructor to IMethodDecorator implementation, all is working fine! 


So basically the solution was to remove all references to  MethodDecorator and all implimitations, adding MethodDecoratorEx package and referencing the dlls manually from the package folder.

**Comment by SimonCropp** [comment]
closing this as stale. please raise a new issue if this is still a problem
