### ISSUE TITLE
Unhandled exception occurred - Xamarin Forms

### ISSUE THREAD

**Issue by farax** [Fody/MethodDecorator#41]
Hi all, 

I am trying out Fody for a Xamarin Forms app. However, I keep getting "Unhandled Exception Occurred". Now I tried the same code (note the versions of MD.Fody since I could not get the latest version to work) in a console app and everything worked like a charm. Any pointers as to what I am doing wrong? I have attached the sample code. 

[App1.zip](https://github.com/Fody/MethodDecorator/files/370844/App1.zip)

**Comment by vlkam** [comment]
Try to do this:
1. Take clean configuration of your application without Fody MethodDecorator
2. Install MethodDecorator.Fody.VS2015
It's work for me in Xamarin iOs and Xamarin Android

**Comment by SimonCropp** [comment]
i dont have Xamarin  set up. happy to accept a PR that fixes this
