### ISSUE TITLE
Configurable Parameter to Active/Passive

### ISSUE THREAD

**Issue by bahadirbal** [Fody/MethodDecorator#44]
Hi All,

I write my method decorator and add to my code as attribute. But I want to activate or make passive according to deployment environment by build action. Is there any kind of action/configurable parameter? 

Thanks,

**Comment by alexeysuvorov** [comment]
Can compile time if help you with it? https://msdn.microsoft.com/en-us/library/4y6tbswk.aspx

**Comment by SimonCropp** [comment]
closing this as stale. please raise a new issue if this is still a problem
