### ISSUE TITLE
How to get return Value?

### ISSUE THREAD

**Issue by Schenz** [Fody/MethodDecorator#46]
This is the closest I've seen that allows me to decorate methods and insert boiler plate code.  However, specifically for logging, I would like to capture the returned object from the wrapped method and log that as well.

It does not appear that this has been implemented, and I'm a bit lost on where to add it if I fork.

Guidance would be appreciated.

**Comment by icnocop** [comment]
See https://github.com/csnemes/tracer

**Comment by SimonCropp** [comment]
closing this as stale. please raise a new issue if this is still a problem
