### ISSUE TITLE
Teamcity Build failing with multiple mscorlib versions

### ISSUE THREAD

**Issue by yossib613** [Fody/MethodDecorator#48]
Hi,

We've started using Fody MethodDecorator...
In VS2015 it builds and runs OK, but when we try to build the project in Teamcity we get the following error.....
Does anyone have any suggestions as to the cause and what we can do to solve this?
Build server is running TC version 10.

Thanks
Yossi
 ```
[Fody.WeavingTask]   Fody: Weaver E:\Build\Code\.........\MethodDecorator.Fody.0.9.0.6\MethodDecorator.Fody.dll'.
[Fody.WeavingTask]   Fody:   Initializing weaver
[Fody.WeavingTask]   Fody:   Loading 'E:\Build\Code\......\Packages\MethodDecorator.Fody.0.9.0.6\MethodDecorator.Fody.dll' from disk.
[Fody.WeavingTask]     Fody/MethodDecorator:   Executing Weaver 

[Fody.WeavingTask] Fody: An unhandled exception occurred:
Exception:
Error occured during IL weaving. The new assembly is now referencing more than one version of mscorlib: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
StackTrace:
   at ModuleWeaver.Execute()
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 161
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 82
Source:
MethodDecorator.Fody
TargetSite:
Void Execute()
```

**Comment by alansingfield** [comment]
I removed that mscorlib multiple version check - if someone could explain why it is necessary then I'll put it back in. I've not seen any adverse affects from its removal. You'll have to build from source or wait for the Nuget to be updated.

**Comment by icnocop** [comment]
I've added `appveyor.yml` in https://github.com/Fody/MethodDecorator/pull/64 to successfully build the NuGet package in AppVeyor.
