### ISSUE TITLE
Allow method decorating on entire assembly with an assembly attribute.

### ISSUE THREAD

**Issue by brianpelton** [Fody/MethodDecorator#5]
It would be nice if we could use an assembly attribute and have the method decorator work on all types in the assembly rather than having to put the attribute on each method.

I tried to copy the type finding logic from MethodTimer but I kept getting exceptions. I'll take another stab at it when I have some more time but if someone else knows an easy way to do this, seems like it would be useful.

**Comment by alexeysuvorov** [comment]
Same as https://github.com/Fody/MethodDecorator/issues/17
