### ISSUE TITLE
Interception

### ISSUE THREAD

**Issue by matkoch** [Fody/MethodDecorator#50]
There seems to be no way to actually intercept a method invocation (which I rather expected :/). Is there any reason for that? If not, and you agree on doing this, I could make a PR as soon as I have some time.

By interception I'm talking about something like this: http://doc.postsharp.net/method-interception

**Comment by icnocop** [comment]
See https://github.com/BrunoJuchli/StaticProxy.Fody or https://github.com/kswoll/sexy-proxy

**Comment by SimonCropp** [comment]
closing this as stale. please raise a new issue if this is still a problem

**Comment by matkoch** [comment]
reopen please
