### ISSUE TITLE
Update to Fody Version 2

### ISSUE THREAD

**Issue by SimonCropp** [Fody/MethodDecorator#52]
Fody Version 2 is out and you will need to do an update for your addin to be usable with it

Specifically:

 * Update to the newest Fody.Cecil nuget
 * Change the min dependency range for Fody to be at least 2.0

 Please ping me if u need help

**Comment by alexdrl** [comment]
Hello, we are looking for alternatives to PostSharp for AOP in a .NET Core scenario.
We have looked in to this project and we have some questions.

Could Fody.MethodDecorator weave an .NET Standard assembly? 

Could a .NET Standard assembly contain some MethodDecorators?

I looked at the code and saw some mscorlib references, and .NET 2.0 support so I'm not sure that the project and tests are going to be easily migrated to .NET Standard.
Thank you in advance.

**Comment by ChaseFlorell** [comment]
I'm pretty sure https://github.com/Fody/MethodDecorator/pull/54 addresses this. We're just anxiously awaiting the nuget release.

**Comment by jasmineanderson** [comment]
Any update on when this will be resolved?

**Comment by SimonCropp** [comment]
@alexeysuvorov do u still want to own this project? or should i put out a call for new owners?

**Comment by alexeysuvorov** [comment]
@SimonCropp I've changed technological stack completely to mobile development and switched from engineering track to management, so I will not be able to maintain this project anymore. Sorry.

**Comment by halittiryaki** [comment]
@SimonCropp 

tried all kind of version combinations via nuget, but cant get rid of the exception.

> Severity Code Description Project File	Line	Suppression State Error Fody: The weaver assembly 'MethodDecorator.Fody, Version=0.9.0.4, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll (cecilReference.Version). At least version 0.10 is expected. The weaver needs to add a NuGet reference to FodyCecil version 2.0.				

current installed package versions:

- Fody 2.1.3
- FodyCecil 2.1.3
- MethodDecorator.Fody 0.9.0.6
- MethodDecorator.Fody.VS2015 0.9.0.7

thanks

**Comment by Kazpers** [comment]
@SimonCropp Can we get this pushed to NuGet, please?

**Comment by wocar** [comment]
same as @halittiryaki, is there any work arround for this @SimonCropp ?

**Comment by halittiryaki** [comment]
@Kazpers @wocar 
this package is your friend: [MethodDecorator.Fody.PP](https://www.nuget.org/packages/MethodDecorator.Fody.PP/0.9.1.6)

you will need to `CopyLocal` manually the `MethodDecoratorInterfaces` in your  projects references after you install the nuget package.

**Comment by ChuckBryan** [comment]
@SimonCropp The Code looks like it was updated a while ago, but the version on NuGet is outdated. Would be able to push this version out to NuGet? Or is there something else that needs to happen?

Many Thanks!!
