### ISSUE TITLE
Please fix this error

### ISSUE THREAD

**Issue by javorbg** [Fody/MethodDecorator#53]
MSBUILD : error : Fody: The weaver assembly 'MethodDecorator.Fody, Version=0.9.0.4, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll (cecilReference.Version). At least version 0.10 is expected. The weaver needs to add a NuGet reference to FodyCecil version 2.0.

**Comment by javorbg** [comment]
I found reason for this error. This is because in MethodDecorator.Fody use old references to Mono.Cecil version 0.9.6.1 in the directory of Fody project the version of Mono.Cecil  (Fody\Lib\Cecil) is 0.10.0.0-beta5

**Comment by valdetero** [comment]
I think this is the same as issue #52

**Comment by SimonCropp** [comment]
closing as duplicate
