### ISSUE TITLE
Out of date version of Mono.Cecil.dll

### ISSUE THREAD

**Issue by rickomax** [Fody/MethodDecorator#55]
When trying to compile my assembly:

Fody: The weaver assembly 'MethodDecorator.Fody, Version=0.9.0.4, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll (cecilReference.Version). At least version 0.10 is expected. The weaver needs to add a NuGet reference to FodyCecil version 2.0.

**Comment by ChaseFlorell** [comment]
This is a duplicate of #52
