### ISSUE TITLE
Does this project need a new maintainer

### ISSUE THREAD

**Issue by SimonCropp** [Fody/MethodDecorator#56]
@citizenmatt @alexeysuvorov 

So i  have pushed a few minor things to this repo over the years. but i dont really consider myself an owner. I dont actively use the project and do not actively monitor the issues. 

From looking at the history am i safe in assuming neither of you are interested in actively maintaining this moving forward?

Do we need to put a call out for other maintainers?

**Comment by ChaseFlorell** [comment]
@SimonCropp thank you for having the self-awareness to bring this up. You've built a fantastic tool and we use it in our app for all of our analytics. I hope someone steps up (sadly I cannot), as Fody has moved forward and no longer supports MethodDecorator in it's current state.

**Comment by Kazpers** [comment]
@SimonCropp While I want to use the package for Aspects I'm not experienced enough with IL Weaving to take on maintaining it. The package seems phenomenal though. The only maintained fork I can see is by @sstronin so maybe he'd be interested?

**Comment by mfkl** [comment]
Any update on this? Anyone volunteering as maintainer? 
Would be nice to have a new version .NET standard 2.0 compliant pushed to nuget.
Let me know if I can help.

**Comment by reflection-emit** [comment]
Just a side note and also shameful self-advert... I actually made a direct competitor to this add-in
[NuGet](https://www.nuget.org/packages/Cauldron.Interception.Fody/)
[GitHub](https://github.com/Capgemini/Cauldron/tree/master/New/Fody)
I recently made it .NET Standard 2.0 capable... And it can do more than just intercepting a Methods.

**Comment by Kazpers** [comment]
@reflection-emit For what it's worth your code looks really interesting (and not just the Interceptor module), however the almost complete lack of documentation and it being not just .NET Standard 2.0 capable - but requiring it - are issues. The last one leaves those of us (a lot of people) still maintaining a 4.5 codebase in the cold and the first just means it is a LOT of work to use it because you almost have to read all the code to figure things out.

But that's all off-topic here, I guess.

**Comment by reflection-emit** [comment]
I just pushed support for NET45 for the interceptor… I have to write Unit test for it though. 😊 So bext version will have it.
Sorry for Off-Topic again.


________________________________

Firma: Capgemini Deutschland GmbH
Aufsichtsratsvorsitzender: Antonio Schnieder • Geschäftsführer: Dr. Michael Schulte (Sprecher) • Jost Förster • Dr. Peter Lempp • Dr. Volkmar Varnhagen

Amtsgericht Berlin-Charlottenburg, HRB 98814
This message contains information that may be privileged or confidential and is the property of the Capgemini Group. It is intended only for the person to whom it is addressed. If you are not the intended recipient, you are not authorized to read, print, retain, copy, disseminate, distribute, or use this message or any part thereof. If you receive this message in error, please notify the sender immediately and delete all copies of this message.

**Comment by icnocop** [comment]
Hi @SimonCropp,

I'm not sure I can play an active role, but I created PR https://github.com/Fody/MethodDecorator/pull/64 which contains appveyor.yml which can be used to verify that tests pass with each new pull request.

I think having a CI server is an important step to have a maintainable project.

Thank you.

**Comment by Annoyingselect2issue** [comment]
based on @ChaseFlorell's comment, do we know if MethodDecorator's will be corrected/worked on?

**Comment by an-dr-eas-k** [comment]
Good question from the OP. One year later not much has happend. Any news on this?

**Comment by Annoyingselect2issue** [comment]
I gave up and used MrAdvice which did exactly what I was looking for

**Comment by SimonCropp** [comment]
closing this as stale. please raise a new issue if this is still a problem
