### ISSUE TITLE
Return custom value

### ISSUE THREAD

**Issue by alexrait** [Fody/MethodDecorator#59]
Is there a way to force the method return some value based on argument checks?

**Comment by icnocop** [comment]
See https://github.com/BrunoJuchli/StaticProxy.Fody or https://github.com/kswoll/sexy-proxy

**Comment by sstronin** [comment]
My fork at https://github.com/sstronin/MethodDecorator does support access to parameters and setting return value with or without actual method execution. There's also important fix of possible executable corruption when short jump becomes long as result of decorating.

**Comment by SimonCropp** [comment]
closing this as stale. please raise a new issue if this is still a problem
