### ISSUE TITLE
Paket Compatibility

### ISSUE THREAD

**Issue by megafinz** [Fody/MethodDecorator#60]
Currently there are `install.ps1` and `uninstall.ps1` scripts which Paket (as long as any other CLI tool) doesn't support. My main complaint is that `Fody_ToBeDeleted.txt` file is added to every project that uses the package, so I have to manually delete those files each time I install or update packages since that doesn't happen automatically due to the fact that `install.ps1` is not executed.

**Comment by SimonCropp** [comment]
Send u a pr that removes those files

**Comment by megafinz** [comment]
Sorry, not sure what means. A PR to me?

**Comment by SimonCropp** [comment]
https://help.github.com/articles/about-pull-requests/

**Comment by megafinz** [comment]
But I don't have a fork or anything. I don't see any notifications about the PR, also there is nothing in my profile stats about the PR. Where do I look for it?

**Comment by SimonCropp** [comment]
https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by megafinz** [comment]
This isn't very helpful. What do I need to do?

**Comment by megafinz** [comment]
Do you actually mean that **I** need to remove those files myself and then send **you** a PR so you can merge it in the upstream?

**Comment by SimonCropp** [comment]
@megafinz yep

**Comment by megafinz** [comment]
Created PR https://github.com/Fody/MethodDecorator/pull/63.
