### ISSUE TITLE
Can Fody be used for handling exceptions?

### ISSUE THREAD

**Issue by MrYossu** [Fody/MethodDecorator#66]
Not actually an issue, more of a question, but I wasn't sure where else to ask.

We have a mature WPF desktop application that has a central global exception handler, which we hook up by doing the following in the Application_Statrtup event of App...

`Current.DispatcherUnhandledException += CurrentDispatcherUnhandledException;`

Our CEO suggested to me that we should be using the Fody method decorator to handle the exceptions instead.

I've looked through the sample code here, and done some searching, but I can't see any particular advantage of using Fody in this way.

In particular, one problem we have been addressing is that exception handling like the above breaks the flow of execution, meaning that the code in `CurrentDispatcherUnhandledException()` doesn't know the context of how the exception was raised, so can't make an intelligent decision about what to do next. The CEO seemed to think that Fody could help here.

Anyone able to enlighten me?

**Comment by SimonCropp** [comment]
closing this as stale. please raise a new issue if this is still a problem

**Comment by MrYossu** [comment]
What's the point in closing it and opening a new one with the same question? Why not just leave it open?

More to the point, do you have any comment on the question?

Thanks

**Comment by SimonCropp** [comment]
> What's the point in closing it and opening a new one with the same question? Why not just leave it open?

happy to reopen if it looks like it will progress. 

>  Why not just leave it open?

https://github.com/probot/stale#is-closing-stale-issues-really-a-good-idea

> More to the point, do you have any comment on the question?

not really, i have never used MethodDecorator, and as such would need to do some research to work out if what you ask is possible. but that is research you could do.

**Comment by MrYossu** [comment]
> but that is research you could do

I did, plenty of it, but couldn't find anything, which is why I asked here.

Never mind, thanks anyway
