### ISSUE TITLE
Build Error after adding MethodDecorator.Fody to the project

### ISSUE THREAD

**Issue by nagarjunan** [Fody/MethodDecorator#67]
Error Fody: The weaver assembly 'MethodDecorator.Fody, Version=0.9.0.4, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll 0.9.6.0. At least version 0.10 is expected. The weaver needs to add a NuGet reference to FodyCecil version 3.0.			

After Installing MethodDecorator.Fody from Nuget I am getting above error. Please suggest me How to fix this issue? Thanks in advance..

**Comment by alexbrillant** [comment]
Same issue
