### ISSUE TITLE
Can't view static variables in debug mode

### ISSUE THREAD

**Issue by JamesFlames** [Fody/MethodDecorator#77]
Fody 3.3.2
MethodDecorator.Fody 1.0.2
Visual Studio 2017 4.7.03062
.NetFramework 4.6.2

When static variables are used in a MethodDecorator weaved assembly then when stepping through in debug mode then those static variables cannot be viewed via either hover over or the watch window. If the static variable is in the same class you are currently debugging then it can be viewed. The error occurs when the static variable you are trying to view in the watch window (or hover over) is in a different class to the one the debug cursor is currently in. As soon as you remove weaving then you can once again view static variables in any class anywhere.

The error when you put the static variable into your watch window is:

StaticTest.MyIntProperty | error CS0103: The name 'StaticTest' does not exist in the current context |

**Comment by SimonCropp** [comment]
@JamesFlames did you read the issue template https://github.com/Fody/MethodDecorator/blob/master/.github/ISSUE_TEMPLATE/bug_report.md  ?
