### ISSUE TITLE
Invalid Program when release build

### ISSUE THREAD

**Issue by brianpelton** [Fody/MethodDecorator#8]
I am using MethodDecorator to do some logging on some of my methods.  It worked great until I made a Release build. Then I got exceptions for 'Common Language Runtime detected an invalid program.'

I removed the method decorator attribute usages from the methods and the exceptions went away.

The problem seems similar to https://github.com/Fody/MethodTimer/issues/2.  I also see errors if I use JustDecompile to view the assembly.  The classes that use my IMethodDecorator are not viewable.  The other classes are viewable.

But it is not similar in that my methods are not marked as async. I am using the async targeting pack, but the specific methods that were causing the errors are 'public virtual void'. And another strange thing is that other methods using the IMethodDecorator are not causing problems.

A workaround is to apply the [Conditional("DEBUG")] attribute to tje IMethodDecorator attribute and then the release build works fine -- without the method decorator functionality.

**Comment by demyte** [comment]
@SimonCrop 

This is still an issue for me when using MethodDecorator.Ex when compiled in Release with the following project properties set:
- Define Debug constant  OFF
- Define Trace constant  ON
- Platform target:  ANY CPU
- Optimize code OFF <- This is the guy causing it, I think, from trial and error changing project properties.
- Advanced > Debug Info  PDB-ONLY

**Comment by robertohuertasm** [comment]
Same issue here! :+1:

**Comment by robertohuertasm** [comment]
@SimonCropp I've created a project so you can reproduce the error: please, find it here and let me know if you need anything: https://gitlab.com/robertohuertasm/fodydecoratorfail

**Comment by robertohuertasm** [comment]
For the moment, I've come up with a workaround that has worked for me. I've found that the methods that were failing were presenting an if clause on top of them with a return and code below (as in an optimized if-else clause). For some reason, this kind of structure seemed to fail. I've extracted the else condition into a method and it worked! So, instead of several lines in the else condition, just one call to a new method encapsulating all the else's lines.

**Comment by oneillci** [comment]
Just wondering if this project is no longer being maintained?
I have just stumbled upon this issue and am going to have to pull my usage of MethodDecorator for the moment until I have time to either debug this issue or rethink my approach.

**Comment by alansingfield** [comment]
I have also been able to reproduce this fault when there is a static constructor which uses other types.
PEVerify reports the error "Attempt to enter a try block with nonempty stack".
I've not quite narrowed down exactly what caused it, but PEVerify was very useful in identifying the broken method. For reference, the code looks OK in Reflector and JustDecompile, but .NET runtime and PEVerify both fail on it.

**Comment by SimonCropp** [comment]
closing this as stale. please raise a new issue if this is still a problem

**Comment by robertohuertasm** [comment]
Why are you closing this without having tested it or given a proper answer in two years? You have a demo repo reproducing the issue that I took the time to put together. Let's at least test it and see if the issue still stands before closing it.

**Comment by SimonCropp** [comment]
@robertohuertasm just to be clear i inherited this project. i dont have the time to fully investigate all the stale issues. is this is still a problem i am happy to accept a PR that fixes it

**Comment by robertohuertasm** [comment]
@SimonCropp sorry if I sounded too harsh, I didn't really mean to. I understand how OSS projects works and we all have a life beyond that.

The thing is that the fact that you don't have the time to investigate it doesn't validate the fact that the issue has to be closed. IMHO the issue should be opened until it's fixed. That's the way some other users can investigate it and provide a proper PR. This issue is really important as the error is not visible until you're using production code. I think at least users should know that they may face some errors while in production even when everything seems to work during development.

**Comment by SimonCropp** [comment]
@robertohuertasm ok i had a look at your repro. it seems a little too complex to complext. can you supply a smaller repro. or better yet a failing unit test

**Comment by SimonCropp** [comment]
also a note on stale issues https://github.com/probot/stale#is-closing-stale-issues-really-a-good-idea

**Comment by robertohuertasm** [comment]
@SimonCropp I'll try to give it a try again but the project was really the simplest one I could build to reproduce the issue I was having. There are only 3 classes.  I will provide a README with the steps to follow so we can work on it.

**Comment by SimonCropp** [comment]
@robertohuertasm ideally i would like a PR that fixes the issue.

**Comment by SimonCropp** [comment]
@robertohuertasm btw if u want to take ownership if this project i am happy to transfer

**Comment by robertohuertasm** [comment]
Thanks @SimonCropp but I don't have so much time. I'm already maintaining two OSS projects and I barely can manage to do it.

**Comment by SimonCropp** [comment]
@robertohuertasm  https://www.nuget.org/profiles/simoncropp   ;)

**Comment by robertohuertasm** [comment]
OMG! :scream: I'd buy your book on how to manage your time right away! :stuck_out_tongue_winking_eye: My sincerest respect and appreciation to you!

**Comment by SimonCropp** [comment]
@robertohuertasm lol thanks

BTW i took another look at your repro. it is using `MethodDecoratorExAsync.Fody` which is not this project

**Comment by SimonCropp** [comment]
@demyte "MethodDecorator.Ex" is not this project
