### ISSUE TITLE
Async equivalents of OnEntry and OnExit

### ISSUE THREAD

**Issue by StevenRasmussen** [Fody/MethodDecorator#80]
Is there support for async versions... for example:
- `Task OnEntryAsync()`
- `Task OnExitAsync()`

From my searching it looks like there is some support for async error handling but not async equivalents of those methods.

If these are not supported, would you be open to accepting a PR to support this?  It makes sense to me that perhaps a new interface would be created called 'IAsyncMethodDecorator' and then propagate that through the pipeline accordingly.

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by SimonCropp** [comment]
@ColonelBundy @StevenRasmussen happy to spend more time on this once you become patrons
